import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.BanachAlgebraTechniquesAppliedFunctionsFoundationCanonicalLaneLean.BanachAlgebraFoundation
import HautevilleHouse.BanachAlgebraTechniquesAppliedFunctionsFoundationCanonicalLaneLean.GelfandTransform
import HautevilleHouse.BanachAlgebraTechniquesAppliedFunctionsFoundationCanonicalLaneLean.FunctionalCalculus

namespace HautevilleHouse
namespace BanachAlgebraTechniquesAppliedFunctionsFoundationCanonicalLaneLean

def ConstrainedBanachAlgebraClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_banach_algebra_endgame (A : AdmissibleClass) :
    ConstrainedBanachAlgebraClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end BanachAlgebraTechniquesAppliedFunctionsFoundationCanonicalLaneLean
end HautevilleHouse